### ISSUE TITLE
Type seats

### ISSUE THREAD

**Issue by zornitsayohanova** [OmarMahili/SeatchartJS#35] opened 2021-11-29 18:38 UTC
Hello, how can type seats be shown, without actually be selected ("clicked"), but only with a changed background colour? Thanks.

**Comment by omahili** [comment] 2021-12-01 12:01
At the moment the library does not allow it, but it's in the todo list:

> Add 'static' mode where seat types are defined by default

I think I'll work on it when I have time, but first I need to complete the porting to typescript (branch `feature/typescript`).

**Comment by omahili** [comment] 2021-12-01 12:09
Hi! I think this is a duplicate of #26. As I said there it's in the to-do list. I know it's been a while  😟  but when I have time I'll merge the typescript porting and work on it.

**Closed as completed** 2021-12-01 12:10 UTC
Labels: enhancement

**Comment by zornitsayohanova** [comment] 2021-12-01 14:11
Oh well, I needed a solution very fast, so I changed the code and all works fine now. :D 
When a seat is unclicked, it gets painted with the colour of its category (in your code it becomes green, which is the colour of "Reduced") and it is also deleted right away from the basket. Still, thanks for the response. :)))

**Comment by omahili** [comment] 2021-12-01 15:41
Nice, happy to hear that! With some tweaks it's definitely possible.
